import GenCPP

GenCPP.generate_callwrapper_ipp('details/ThreadHandlerSetParams.ipp', """
template <{template}>
void setParams({params}) const {
	params_ = params_ptr(new params_type({call}));
}
""", 5, False, True)

